version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    versioning-strategy: increase
    groups:
      eslint:
        applies-to: version-updates
        patterns:
          - 'eslint*'
        update-types:
          - 'minor'
          - 'patch'
      all:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: 'version-update:semver-major'
