version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/first-package"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/second-package"
    schedule:
      interval: "weekly"
