version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/first-package"
    schedule:
      interval: "weekly"
    groups:
      first-package:
        applies-to: version-updates
        update-types:
          - 'major'
          - 'patch'
          - 'minor'
        patterns:
          - '*'
  - package-ecosystem: "npm"
    directory: "/second-package"
    schedule:
      interval: "weekly"
    groups:
      second-package:
        applies-to: version-updates
        update-types:
          - 'major'
          - 'patch'
          - 'minor'
        patterns:
          - '*'