version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    versioning-strategy: increase
    groups:
      eslint:
        applies-to: version-updates
        patterns:
          - 'eslint*'
      all:
        applies-to: version-updates
        patterns:
          - '*'